language: php
dist: bionic
sudo: false

matrix:
  fast_finish: true
  include:
    - php: "7.2"
      env: TYPO3_VERSION=^9 RUN_SONAR_SCANNER=1
    - php: "7.3"
      env: TYPO3_VERSION=^9

addons:
  sonarcloud:
    token:
      secure: "UtkUbxuS862JTB/Zy5HpjoIGYTOl39uKmbfwgKI6/sI5/eEcvTuXWzRzgDoZ2ToVkUX5Wbq9Q57W+0eUtAoohjFXfLPGuA9yRorv0TAufMp4u64ANzla55c+OCTRGuwXyQ9DlKru+8YXsl80irfBdiV2PTvL6xW20HTmhadoroTfuo3FEGYosOXQqK2krX68RPE8JQlNNAN9fFz661vGwiEbn9azl2dtzFFBtDBG3VP2KWhlPOJTtv7bUgyT9eNtDuuu+azK6MmaC2oZRhxwMOqU6gBVmcJOkD+chOlG6HP7iUYiHO1cF02C4VpKIsBxpqLdzwEqOYo93+PvZkLRovJ+8hl7H1RXGab3kfMcGCjSb0MKh8lTevlGLJiIJawcrwJbEYhinr9yPD/OWnaaZKJwxfwEdPe/YbsE6c/sXZFn/Aw4er/279S+wnDtBB/ocKIxeEpx5QKBaZX83vi4edykoI6yBxmiq2mEAMsLtift5g1upSPPKRSUIYIRVgMx2no/tNFnWg6s57QLtZmcitdTnNeELxT+PaDiHL75CZfVdpGmclXrLPwU221deiiy/6bvDMLQhKDPxzDKe6XfZP+JCGb3q+2lH5Ppmju/TsF6czlOsKYw0IHW8XxllvEleFzr/PL5t6iEp7yBDDBWufLDb+HV1ye3S1Eu1Tt3S5w="

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.sonar/cache

before_install:
  - composer self-update
  - composer --version

before_script:
  - composer require typo3/cms-core=$TYPO3_VERSION
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.Build/web

script:
  - find . -name \*.php  ! -path "./.Build/*" -exec php -d display_errors=stderr -l {} > /dev/null \;
  - .Build/bin/phpunit -c Tests/phpunit.xml.dist --log-junit .Build/logs/phpunit.xml --coverage-text --coverage-clover .Build/logs/clover.xml
  - if [[ $RUN_SONAR_SCANNER == "1" ]]; then sonar-scanner -Dsonar.projectVersion=$TRAVIS_TAG; fi
