services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Brotkrueml\JobRouterConnector\:
    resource: '../Classes/*'

  Brotkrueml\JobRouterConnector\Command\GenerateKeyCommand:
    tags:
      - name: 'console.command'
        command: 'jobrouter:connector:generatekey'
        schedulable: false
